# Generated by Django 5.1.2 on 2024-12-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0004_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
