# Generated by Django 5.1.2 on 2024-11-04 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crqsdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='crqsdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='crqsdata',
            name='hours',
        ),
        migrations.AddField(
            model_name='crqsdata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crqsdata',
            name='week',
            field=models.CharField(max_length=100),
        ),
    ]
