# Generated by Django 5.1.2 on 2024-11-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsapp', '0003_rename_datetime_crqsdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crqsdata',
            name='count_of_issues',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crqsdata',
            name='number_of_samples',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crqsdata',
            name='parameter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crqsdata',
            name='score',
            field=models.CharField(help_text='Quality assessment score', max_length=100),
        ),
        migrations.AlterField(
            model_name='crqsdata',
            name='speed',
            field=models.CharField(max_length=50),
        ),
    ]
