# Generated by Django 5.1.2 on 2024-11-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsapp', '0004_alter_crqsdata_count_of_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crqsdata',
            name='parameter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crqsdata',
            name='temperature',
            field=models.CharField(max_length=50),
        ),
    ]
