# Generated by Django 5.1.2 on 2024-11-16 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsapp', '0005_alter_crqsdata_parameter_alter_crqsdata_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('week', models.CharField(max_length=100)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=50, verbose_name='SKU')),
                ('Target', models.CharField(max_length=50)),
                ('Achieved', models.CharField(max_length=50)),
                ('batch_number', models.CharField(max_length=50)),
                ('variant', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, help_text='Additional comments', null=True)),
                ('assessor', models.CharField(help_text='Person responsible for assessment', max_length=100)),
            ],
        ),
    ]
