# Generated by Django 5.1.2 on 2024-11-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionsapp', '0006_packingdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packingdata',
            old_name='Achieved',
            new_name='achieved',
        ),
        migrations.RenameField(
            model_name='packingdata',
            old_name='Target',
            new_name='target',
        ),
    ]
