# Generated by Django 5.1.2 on 2024-11-21 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsapp', '0008_globalproducttable_vimlemonke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vimlemonke',
            name='global_table',
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='batch_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='batch_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='batch_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='checked_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='done_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='hash',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='magadi_batch_number',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='magadi_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='stop_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='sulphonic_acid_batch_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='sulphonic_acid_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='verified_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='whiting_batch_number',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vimlemonke',
            name='whiting_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='GlobalProductTable',
        ),
    ]
