# Generated by Django 5.1.2 on 2024-11-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsapp', '0009_remove_vimlemonke_global_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vimlemonke',
            name='batch_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vimlemonke',
            name='start_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vimlemonke',
            name='stop_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
