# Generated by Django 5.1.2 on 2024-11-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsapp', '0010_alter_vimlemonke_batch_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vimlemonke',
            name='magadi_batch_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vimlemonke',
            name='whiting_batch_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
