# Generated by Django 5.1.2 on 2024-11-22 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionsapp', '0011_alter_vimlemonke_magadi_batch_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VimLavenderKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('hash', models.FloatField(null=True)),
                ('batch_number', models.CharField(max_length=20, null=True)),
                ('start_time', models.CharField(max_length=20, null=True)),
                ('stop_time', models.CharField(max_length=20, null=True)),
                ('batch_time', models.CharField(max_length=20, null=True)),
                ('whiting_quantity', models.FloatField(null=True)),
                ('whiting_batch_number', models.CharField(max_length=20, null=True)),
                ('magadi_quantity', models.FloatField(null=True)),
                ('magadi_batch_number', models.CharField(max_length=20, null=True)),
                ('tcca_quantity', models.FloatField(null=True)),
                ('tcca_batch_number', models.CharField(max_length=20, null=True)),
                ('sulphonic_acid_quantity', models.FloatField(null=True)),
                ('sulphonic_acid_batch_number', models.CharField(max_length=20, null=True)),
                ('katio_quantity', models.FloatField(null=True)),
                ('katio_batch_number', models.CharField(max_length=20, null=True)),
                ('batch_size', models.FloatField(null=True)),
                ('pressure', models.FloatField(null=True)),
                ('done_by', models.CharField(max_length=20, null=True)),
                ('checked_by', models.CharField(max_length=20, null=True)),
                ('verified_by', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vimlemonke',
            name='hash',
            field=models.FloatField(null=True),
        ),
    ]
